#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Slow queries
graph_category postgresql
graph_info The total number of slow queries
graph_vlabel total
total.label total
EOM
        exit 0;;
esac

previous=`cat $MUNIN_STATEFILE  || echo 0`
current=`cat /var/log/postgresql/postgresql-9.5-main.log | grep -o 'tilery@tilery LOG:  duration: ' | wc -l`
if [ "$previous" -gt "$current" ]; then  # Log file has rotated?
    previous=0
fi
total="$((current - previous))"
echo $current > $MUNIN_STATEFILE

printf "total.value "
printf $total
